version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threat-detection-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./data/uploads:/app/data/uploads
      - threat-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - threat-detection-network

  # Frontend Dashboard
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: threat-detection-dashboard
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - threat-detection-network

volumes:
  threat-data:
    driver: local

networks:
  threat-detection-network:
    driver: bridge
